vault:
  address: http://localhost:8200

  # userpass authentication
  # authMethod: userpass
  # authMount: userpass

  # OIDC authentication
  authMethod: oidc
  authMount: oidc
  callbackPort: 8250
secrets:
- path: mysecret
  mount: secret
  prefix: MY_APP_
