name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
    - name: check version
      env:
        RELEASE_TAG: ${{ github.ref_name }}
      run: |
        if ! grep $RELEASE_TAG flake.nix; then
          echo "Version not found in flake.nix"
          exit 1
        fi
    - name: setup
      run: make setup
    - name: build all
      env:
        RELEASE_TAG: ${{ github.ref_name }}
      run: make all
    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: bin

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: artifacts
      uses: actions/download-artifact@v4
      with:
        name: release
        path: bin
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/*"